### ISSUE TITLE
Step 5 Tracking step - Python str error 

### ISSUE THREAD

**Issue by dschof** [ox-vgg/chimpanzee-tracking#14]
<img width="569" alt="image" src="https://github.com/ox-vgg/follow-things-around/assets/19774512/e8210c0e-ad9d-453f-96e5-43552d3fd05d">

Error encountered at tracking step 5: 'TypeError: expected str, bytes or os.PathLike object, not list'

**Comment by carandraug** [comment]
Thank you for the report. Now fixed in aa5958c. Wrong variable used in a recent refactoring. Closing as fixed.
